import Head from 'next/head';
import Link from 'next/link';

import styles from '../styles/Home.module.scss';

import MainFrame from '../components/MainFrame';

export default function Home() {
	return (
		<MainFrame>
			<Head>
				<title>Bruno Remeikis</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<main className={styles.container}>
				<div>
					<p className={styles.p1}>Olá!</p>
					<p className={styles.p2}>Eu sou o <span>Bruno</span>,</p>
					<p className={styles.p2}>dev Full Stack</p>

					<div className={styles.btnSobre}>
						<Link href="/about">Sobre mim</Link>
					</div>
				</div>

				{/* Main image */}
				<span className={styles.mainPic} />
			</main>
		</MainFrame>
	)
}
