import Head from 'next/head';
import Link from 'next/link';

import styles from '../styles/Test.module.scss';

import MainFrame, { PageEnum } from '../components/MainFrame';
import { getImagePath, technologies } from '../utils/technologies';
import Image from 'next/dist/client/image';

import { IoMdDownload } from "react-icons/io";
import { RiFileDownloadLine } from "react-icons/ri";
import { TbFileDownload } from "react-icons/tb";

import { Card } from '../components/Card';
import { Emojis } from '../components/Card/CardIcon';


// import Flag from 'react-flagpack';

const Home: React.FC = () =>
(
	<div className={styles.page}>
		<div className={styles.pageScroll}>

			<Head>
				<title>Bruno Remeikis</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<h1>Bruno Coutinho Remeikis</h1>

			{/* INICIO - HOME */}
			<div className={`${styles.section} ${styles.homeSection}`}>
				<div className={styles.container}>
					<main className={styles.content}>
						{/* <Link href="#about">About</Link> */}
						<div className={styles.mainText}>
							<p className={styles.p1}>Olá!</p>
							<p className={styles.p2}>Eu sou o <span>Bruno</span>,</p>
							<p className={styles.p2}>dev Full Stack</p>

							<div className={styles.btnSobre}>
								<Link href="#about">Sobre mim</Link>
							</div>
						</div>

						{/* Main image */}
						<span className={styles.mainPic} />
					</main>
				</div>
			</div>

			{/* SOBRE - ABOUT */}
			<div id="about" className={`${styles.section} ${styles.aboutSection}`}>
				<div className={styles.polygon2} />
				<div className={styles.aboutContent}>
					<div className={styles.about__col}>

						<h2>Sobre mim</h2>
						<div className={styles.about__text}>
							<p>Me chamo <span>Bruno Coutinho Remeikis</span>.</p>
							<p>Sou desenvolvedor Full Stack.</p>
							<p>Sou de Vitória - ES.</p>
							<p>
								Me formei como Técinco em Desenvolvimeno de Sistemas pelo SENAI. Atualmente,
								curso Bacharelado em Sistemas de Informação pela FAESA.
							</p>
						</div>

						<div className={styles.tecnologies}>
							{Object.entries(technologies).map((item, i) =>
								<div key={i} className={styles.tec}>
									<div className={styles.tec__imgContainer}>
										<Image
											src={getImagePath(item[1].imageName)}
											alt={item[1].name}
											width={45}
											height={45}
										/>
									</div>
									<span className={styles.tec__name}>{item[1].name}</span>
								</div>
							)}
						</div>

						<div className={styles.downloadContainer}>
							<a href="/resume/resume.pdf" className={styles.download} download>
								Download CV <TbFileDownload />
							</a>
						</div>

						{/* <button type="button" onClick={() => {
							fetch('').then(res => console.log(res));
						}}></button> */}
					</div>

					<div className={styles.about__col}>
						{/* ESTUDO */}
						<div className={styles.cards}>
							<Card.Root>
								<Card.Icon emoji={ Emojis.NOTEBOOK } />
								<Card.Info
									title='Técnico em Desenvolvimento de Sistemas'
									institution='SENAI'
									local='Vitória - ES'
									period='2018 - 2019'
								/>
							</Card.Root>

							<Card.Root>
								<Card.Icon emoji={ Emojis.GRADUATION_CAP } />
								<Card.Info
									title='Bacharel em Sistemas de Informação'
									institution='FAESA'
									local='Vitória - ES'
									period='2022 - cursando'
								/>
							</Card.Root>
						</div>

						{/* EMPRESAS */}
						<div className={styles.cards}>
							<Card.Root>
								<Card.Icon emoji={ Emojis.BRIEFCASE } />
								<Card.Info
									title='SEFAZ - Secretaria da Fazenda'
									local='Vitória - ES'
									period='2020 - 2021'
								/>
							</Card.Root>

							<Card.Root>
								<Card.Icon emoji={ Emojis.BRIEFCASE } />
								<Card.Info
									title='CSI - Solução & Tecnologia'
									local='Vitória - ES'
									period='2021 - hoje'
								/>
							</Card.Root>
						</div>

						{/* LINGUAS */}
						<div className={styles.cards}>
							<Card.Root>
								<Card.Icon emoji={ Emojis.RED_BOOK } />
								<Card.Lang
									leitura={3}
									escrita={3}
									conversacao={2}
								/>
							</Card.Root>

							{/* <Card.Root>
								<Card.Icon emoji={ Emojis.GREEN_BOOK } />
								<Card.Lang
									leitura={4}
									escrita={4}
									conversacao={4}
								/>
							</Card.Root> */}
						</div>
					</div>
				</div>

				{/* <div className={styles.polygon} /> */}
			</div>

			<div className={`${styles.section} ${styles.projectsSection}`}>
				<div className={styles.projectImg}>
					{/* <Image src='/projects/calendario.png' layout='fill' /> */}
				</div>
			</div>

			<div className={styles.section}>
				<h2>AAAA</h2>
			</div>

			<footer>
				<p>Ultima atualização</p>
				<p>fevereiro de 2024</p>
			</footer>
		
		</div>
	</div>
);

export default Home;